name: Test and Build Website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  website-build:
    runs-on: ubuntu-latest
    needs: cargo-test
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-lesss
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: build wasm
        run: wasm-pack build --release
        working-directory: ./wasm
      - name: yarn install
        run: yarn install
        working-directory: ./website
      - name: frontend build
        run: yarn run build
        working-directory: ./website
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './website/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-lesss
      - name: Run test
        run: cargo test
  formatter:
    runs-on: ubuntu-latest
    needs: cargo-test
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-lesss
      - name: Format
        run: cargo fmt --all -- --check
  clippy-check:
    runs-on: ubuntu-latest
    needs: cargo-test
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-lesss
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
